pipeline {
    agent any

    stages {
        stage('Unit Test - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir ('bugtracker-backend'){
                    sh '''
                        export GOCACHE=/tmp/go-cache
                        export GOPATH=/tmp/go
                        mkdir -p /tmp/go-cache
                        go test -v ./...
                    '''

                }
                
            }
        }
    }
}
